-- Grade 2 background_grade_metrics REPLACEMENT script
-- Generated by generate_background_grade_metrics_sql.py
-- CSV source: Final Data/Component Level Benchmarks.csv
-- Grade 2 INSERT rows: 0

BEGIN;

-- 1. Remove dependent rows that reference grade 2 metrics
DELETE FROM dataset_revision_changes
  WHERE metric_id IN (SELECT id FROM background_grade_metrics WHERE grade_id = 2);

DELETE FROM project_dataset_exclusions
  WHERE metric_id IN (SELECT id FROM background_grade_metrics WHERE grade_id = 2);

UPDATE activity_data
  SET metric_id = NULL
  WHERE metric_id IN (SELECT id FROM background_grade_metrics WHERE grade_id = 2);

-- 2. Delete old grade 2 rows
DELETE FROM background_grade_metrics WHERE grade_id = 2;

-- 3. Insert fresh grade 2 rows from v3 CSV

COMMIT;
