-- Grade 3 & 4 background_grade_metrics REPLACEMENT script
-- Generated by generate_background_grade_metrics_sql.py
-- CSV source: Final Data/Grade 3-4 Detailed.csv
-- Grade 3 & 4 INSERT rows: 0

BEGIN;

-- 1. Remove dependent rows that reference grade 3 & 4 metrics
DELETE FROM dataset_revision_changes
  WHERE metric_id IN (SELECT id FROM background_grade_metrics WHERE grade_id IN (3, 4));

DELETE FROM project_dataset_exclusions
  WHERE metric_id IN (SELECT id FROM background_grade_metrics WHERE grade_id IN (3, 4));

UPDATE activity_data
  SET metric_id = NULL
  WHERE metric_id IN (SELECT id FROM background_grade_metrics WHERE grade_id IN (3, 4));

-- 2. Delete old grade 3 & 4 rows
DELETE FROM background_grade_metrics WHERE grade_id IN (3, 4);

-- 3. Insert new grade 3 & 4 rows from v2 CSV

COMMIT;
