"""
Generate a self-contained SQL INSERT script for electric_decarb_factors.
No database connection required — all FK lookups are done via subqueries.

Run from the backend/ directory:
    python tools/seeds/generate_electric_decarb_sql.py

Output: tools/seeds/electric_decarb_seed.sql
"""
import csv
from pathlib import Path

DATA_DIR = Path(__file__).parent / "data"
OUT_FILE = Path(__file__).parent / "electric_decarb_seed.sql"

REVISION_NAME = "Austroads Benchmarks v1.0 (2026)"

# (csv_filename, factor_type_code, has_region, is_percentage)
CSV_SPECS = [
    ("Final Data/Scope 2 emissions factors (location-based approach) (tCO2e_MWh).csv",  "scope2_location", True,  False),
    ("Final Data/Scope 2 emissions factors (market-based approach) (tCO2e_MWh).csv",    "scope2_market",   False, False),
    ("Final Data/Scope 3 emissions factors (location-based approach) (tCO2e_MWh).csv",  "scope3_location", True,  False),
    ("Final Data/Scope 3 emissions factors (market-based approach) (tCO2e_MWh).csv",    "scope3_market",   False, False),
    ("Final Data/Renewable Power Percentage (market-based approach).csv",               "renewable_pct",   False, False),
]

# CSV jurisdiction name → DB jurisdiction name
JUR_MAP = {
    "Australia":    "Australia",
    "New Zealand":  "New Zealand",
}


def _sql_value(raw: str, is_pct: bool) -> tuple[str, str]:
    """Return (sql_value_literal, sql_qualifier_literal).
    Returns ('NULL', 'NULL') for empty, ('NULL', "'D'") for disclosed-but-withheld.
    """
    s = raw.strip()
    if s == "" or s.upper() == "N/A":
        return "NULL", "NULL"
    if s.upper() == "D":
        return "NULL", "'D'"
    try:
        if is_pct:
            num = float(s.rstrip("%")) / 100.0
        else:
            num = float(s)
        return str(num), "NULL"
    except ValueError:
        return "NULL", "NULL"


def _jur_subq(jur_name: str) -> str:
    safe = jur_name.replace("'", "''")
    return f"(SELECT id FROM jurisdictions WHERE name = '{safe}')"


def _region_subq(jur_name: str, region_name: str) -> str:
    safe_r = region_name.replace("'", "''")
    return f"(SELECT gr.id FROM grid_regions gr JOIN jurisdictions j ON j.id = gr.jurisdiction_id WHERE j.name = '{jur_name.replace(chr(39), chr(39)*2)}' AND gr.name = '{safe_r}')"


def _rev_subq() -> str:
    safe = REVISION_NAME.replace("'", "''")
    return f"(SELECT id FROM dataset_revisions WHERE name = '{safe}')"


def generate() -> None:
    lines: list[str] = []
    lines.append("-- Electric Decarb Factors seed")
    lines.append("-- Generated by tools/seeds/generate_electric_decarb_sql.py")
    lines.append("-- Run AFTER alembic upgrade head\n")
    lines.append(f"-- Dataset revision: {REVISION_NAME}\n")

    rev_subq = _rev_subq()
    total = 0

    for csv_file, ft_code, has_region, is_pct in CSV_SPECS:
        path = DATA_DIR / csv_file
        if not path.exists():
            print(f"WARNING: {csv_file} not found — skipping")
            continue

        lines.append(f"\n-- ── {ft_code} ({csv_file}) ──────────────")

        with open(path, newline="", encoding="utf-8-sig") as f:
            reader = csv.reader(f)
            header = next(reader)

        # Determine year columns (start after Jurisdiction [, Region])
        start_col = 2 if has_region else 1
        year_cols = header[start_col:]

        with open(path, newline="", encoding="utf-8-sig") as f:
            reader = csv.reader(f)
            next(reader)  # skip header
            for row in reader:
                if not row or not row[0].strip():
                    continue

                jur_csv = row[0].strip()
                jur_db = JUR_MAP.get(jur_csv, jur_csv)
                jur_subq = _jur_subq(jur_db)

                if has_region:
                    region_csv = row[1].strip() if len(row) > 1 else ""
                    region_subq = _region_subq(jur_db, region_csv)
                    region_val = region_subq
                else:
                    region_val = "NULL"

                for i, year_str in enumerate(year_cols):
                    year = int(year_str.strip())
                    raw_val = row[start_col + i] if start_col + i < len(row) else ""
                    sql_val, sql_qual = _sql_value(raw_val, is_pct)

                    lines.append(
                        f"INSERT INTO electric_decarb_factors "
                        f"(dataset_revision_id, factor_type_code, jurisdiction_id, region_id, year, value, value_qualifier) "
                        f"VALUES ({rev_subq}, '{ft_code}', {jur_subq}, {region_val}, {year}, {sql_val}, {sql_qual}) "
                        f"ON CONFLICT DO NOTHING;"
                    )
                    total += 1

    with open(OUT_FILE, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"Written {total} INSERT statements to {OUT_FILE}")


if __name__ == "__main__":
    generate()
