"""AUS and NZ Small User Emission Calcs

Revision ID: 0875383bb375
Revises: b1d2e3f4a5b6
Create Date: 2026-04-24 14:25:23.859085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0875383bb375'
down_revision: Union[str, Sequence[str], None] = 'b1d2e3f4a5b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_emissions_nz_results",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column(
            "project_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("project.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "project_stage_instance_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("project_stage_instances.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "project_option_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("project_options.id", ondelete="CASCADE"),
            nullable=False,
        ),
        # The calendar year this row covers
        sa.Column("assessment_year", sa.Integer, nullable=False),
        # VEPM intensities (gCO2e/km) — after linear interpolation
        sa.Column("general_fleet_intensity_gco2e_km",  sa.Numeric(12, 6), nullable=True),
        sa.Column("light_vehicle_intensity_gco2e_km",  sa.Numeric(12, 6), nullable=True),
        sa.Column("heavy_vehicle_intensity_gco2e_km",  sa.Numeric(12, 6), nullable=True),
        # Annual emissions = VKT × intensity / 10^6  (tCO2e)
        sa.Column("general_fleet_emissions_tco2e", sa.Numeric(18, 6), nullable=True),
        sa.Column("light_vehicle_emissions_tco2e", sa.Numeric(18, 6), nullable=True),
        sa.Column("heavy_vehicle_emissions_tco2e", sa.Numeric(18, 6), nullable=True),
        # Sum of the three vehicle types for this year
        sa.Column("total_annual_emissions_tco2e", sa.Numeric(18, 6), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=False),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.UniqueConstraint(
            "project_option_id", "assessment_year",
            name="uq_user_emissions_nz_results",
        ),
    )
    op.create_index("ix_uenz_results_stage",  "user_emissions_nz_results", ["project_stage_instance_id"])
    op.create_index("ix_uenz_results_option", "user_emissions_nz_results", ["project_option_id"])


    op.create_table(
        "user_emissions_aus_small_results",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column(
            "project_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("project.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "project_stage_instance_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("project_stage_instances.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "project_option_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("project_options.id", ondelete="CASCADE"),
            nullable=False,
        ),
        # The calendar year this row covers
        sa.Column("assessment_year", sa.Integer, nullable=False),
        # Emissions intensities (gCO2e/km) from fn_veh_emissions_intensity_aus
        sa.Column("light_vehicle_intensity_gco2e_km",       sa.Numeric(12, 6), nullable=True),
        sa.Column("medium_vehicle_intensity_gco2e_km",      sa.Numeric(12, 6), nullable=True),
        sa.Column("heavy_vehicle_intensity_gco2e_km",       sa.Numeric(12, 6), nullable=True),
        sa.Column("super_heavy_vehicle_intensity_gco2e_km", sa.Numeric(12, 6), nullable=True),
        # Annual emissions = VKT × intensity / 10^6  (tCO2e)
        sa.Column("light_vehicle_emissions_tco2e",       sa.Numeric(18, 6), nullable=True),
        sa.Column("medium_vehicle_emissions_tco2e",      sa.Numeric(18, 6), nullable=True),
        sa.Column("heavy_vehicle_emissions_tco2e",       sa.Numeric(18, 6), nullable=True),
        sa.Column("super_heavy_vehicle_emissions_tco2e", sa.Numeric(18, 6), nullable=True),
        # Sum of all four vehicle types for this year
        sa.Column("total_annual_emissions_tco2e", sa.Numeric(18, 6), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=False),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.UniqueConstraint(
            "project_option_id", "assessment_year",
            name="uq_user_emissions_aus_small_results",
        ),
    )
    op.create_index(
        "ix_ueaus_small_results_stage",
        "user_emissions_aus_small_results",
        ["project_stage_instance_id"],
    )
    op.create_index(
        "ix_ueaus_small_results_option",
        "user_emissions_aus_small_results",
        ["project_option_id"],
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_uenz_results_option", table_name="user_emissions_nz_results")
    op.drop_index("ix_uenz_results_stage",  table_name="user_emissions_nz_results")
    op.drop_table("user_emissions_nz_results")

    op.drop_index("ix_ueaus_small_results_option", table_name="user_emissions_aus_small_results")
    op.drop_index("ix_ueaus_small_results_stage",  table_name="user_emissions_aus_small_results")
    op.drop_table("user_emissions_aus_small_results")
    # ### end Alembic commands ###
