"""Add recycled_content_factors

Revision ID: 0978f35edd0f
Revises: dr01_drop_concrete_mix_tables
Create Date: 2026-05-17 22:22:10.552206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0978f35edd0f'
down_revision: Union[str, Sequence[str], None] = 'dr01_drop_concrete_mix_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recycled_content_factors",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column(
            "jurisdiction_id",
            sa.UUID(),
            nullable=True,
        ),
        sa.Column(
            "emissions_sub_category_id",
            sa.UUID(),
            nullable=True,
        ),
        sa.Column("emissions_source", sa.String(), nullable=False),
        sa.Column("recycled_content_pct", sa.Numeric(), nullable=True),
        sa.Column("reused_content_pct", sa.Numeric(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["jurisdiction_id"],
            ["jurisdictions.id"],
            name="fk_rcf_jurisdiction_id",
        ),
        sa.ForeignKeyConstraint(
            ["emissions_sub_category_id"],
            ["emissions_categories.id"],
            name="fk_rcf_emissions_sub_category_id",
        ),
        sa.PrimaryKeyConstraint("id", name="recycled_content_factors_pkey"),
        sa.UniqueConstraint(
            "jurisdiction_id",
            "emissions_source",
            name="uq_rcf_jurisdiction_source",
        ),
    )
    op.create_index(
        "ix_rcf_jurisdiction_id",
        "recycled_content_factors",
        ["jurisdiction_id"],
    )
    op.create_index(
        "ix_rcf_emissions_sub_category_id",
        "recycled_content_factors",
        ["emissions_sub_category_id"],
    )
    op.create_index(
        "ix_rcf_emissions_source",
        "recycled_content_factors",
        ["emissions_source"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_rcf_emissions_source", table_name="recycled_content_factors")
    op.drop_index("ix_rcf_emissions_sub_category_id", table_name="recycled_content_factors")
    op.drop_index("ix_rcf_jurisdiction_id", table_name="recycled_content_factors")
    op.drop_table("recycled_content_factors")
    # ### end Alembic commands ###
