"""add_renewable_energy_classification

Revision ID: 1a25accd72ec
Revises: a1b2c3d4
Create Date: 2026-05-20 16:51:12.861923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a25accd72ec'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "renewable_energy_classifications",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("dataset_revision_id", sa.UUID(), nullable=True),
        sa.Column("emissions_source", sa.String(), nullable=False),
        sa.Column("classification", sa.String(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["dataset_revision_id"],
            ["dataset_revisions.id"],
            name="fk_rec_dataset_revision_id",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="renewable_energy_classifications_pkey"),
    )
    op.create_index(
        "ix_rec_dataset_revision_id",
        "renewable_energy_classifications",
        ["dataset_revision_id"],
    )
    op.create_index(
        "ix_rec_emissions_source",
        "renewable_energy_classifications",
        ["emissions_source"],
    )
    # Partial unique index: global rows (no revision)
    op.create_index(
        "uq_rec_global_source",
        "renewable_energy_classifications",
        ["emissions_source"],
        unique=True,
        postgresql_where=sa.text("is_active = TRUE AND dataset_revision_id IS NULL"),
    )
    # Partial unique index: revision-scoped rows
    op.create_index(
        "uq_rec_revision_source",
        "renewable_energy_classifications",
        ["emissions_source", "dataset_revision_id"],
        unique=True,
        postgresql_where=sa.text("is_active = TRUE AND dataset_revision_id IS NOT NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_rec_revision_source", table_name="renewable_energy_classifications")
    op.drop_index("uq_rec_global_source", table_name="renewable_energy_classifications")
    op.drop_index("ix_rec_emissions_source", table_name="renewable_energy_classifications")
    op.drop_index("ix_rec_dataset_revision_id", table_name="renewable_energy_classifications")
    op.drop_table("renewable_energy_classifications")
    # ### end Alembic commands ###
