"""add new tables

Revision ID: 36cc2dc6aca5
Revises: dbfef4e7be4e
Create Date: 2026-02-26 20:34:34.999727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '36cc2dc6aca5'
down_revision: Union[str, Sequence[str], None] = 'dbfef4e7be4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('performed_by', sa.UUID(), nullable=True),
    sa.Column('performed_by_org', sa.UUID(), nullable=True),
    sa.Column('performed_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__audit_logs'))
    )
    op.create_index('audit_logs_entity_type_entity_id_performed_at_idx', 'audit_logs', ['entity_type', 'entity_id', 'performed_at'], unique=False)
    op.create_table('joint_ventures',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_on', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_on', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__joint_ventures')),
    sa.UniqueConstraint('name', name=op.f('uq__joint_ventures__name'))
    )
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_on', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_on', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__permissions')),
    sa.UniqueConstraint('name', name=op.f('uq__permissions__name'))
    )
    op.create_table('joint_venture_members',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('joint_venture_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('ownership_pct', sa.Numeric(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('created_on', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_on', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['joint_venture_id'], ['joint_ventures.id'], name=op.f('fk__joint_venture_members__joint_venture_id__joint_ventures')),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk__joint_venture_members__organization_id__organization')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__joint_venture_members')),
    sa.UniqueConstraint('joint_venture_id', 'organization_id', name='joint_venture_members_joint_venture_id_organization_id_key')
    )
    op.create_index('joint_venture_members_joint_venture_id_idx', 'joint_venture_members', ['joint_venture_id'], unique=False)
    op.create_index('joint_venture_members_organization_id_idx', 'joint_venture_members', ['organization_id'], unique=False)
    op.create_table('organization_domains',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_on', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_on', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk__organization_domains__organization_id__organization')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__organization_domains')),
    sa.UniqueConstraint('organization_id', 'domain', name='organization_domains_organization_id_domain_key')
    )
    op.create_index('organization_domains_domain_idx', 'organization_domains', ['domain'], unique=False)
    op.create_table('role_permissions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('created_on', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_on', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk__role_permissions__permission_id__permissions')),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk__role_permissions__role_id__roles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__role_permissions')),
    sa.UniqueConstraint('role_id', 'permission_id', name='role_permissions_role_id_permission_id_key')
    )
    op.create_table('user_roles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('scope_type', sa.String(), nullable=True),
    sa.Column('scope_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_on', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_on', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk__user_roles__role_id__roles')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk__user_roles__user_id__users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__user_roles')),
    sa.UniqueConstraint('user_id', 'role_id', 'scope_type', 'scope_id', name='user_roles_user_id_role_id_scope_type_scope_id_key')
    )
    op.create_table('project_parties',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('joint_venture_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('role_note', sa.String(), nullable=True),
    sa.Column('contract_number', sa.String(), nullable=True),
    sa.Column('created_on', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_on', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['joint_venture_id'], ['joint_ventures.id'], name=op.f('fk__project_parties__joint_venture_id__joint_ventures')),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk__project_parties__organization_id__organization')),
    sa.ForeignKeyConstraint(['project_id'], ['project.project_id'], name=op.f('fk__project_parties__project_id__project')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__project_parties'))
    )
    op.create_index('project_parties_joint_venture_id_idx', 'project_parties', ['joint_venture_id'], unique=False)
    op.create_index('project_parties_organization_id_idx', 'project_parties', ['organization_id'], unique=False)
    op.create_index('project_parties_project_id_idx', 'project_parties', ['project_id'], unique=False)
    op.create_index('project_parties_project_id_joint_venture_id_role_idx', 'project_parties', ['project_id', 'joint_venture_id', 'role'], unique=False)
    op.create_index('project_parties_project_id_organization_id_role_idx', 'project_parties', ['project_id', 'organization_id', 'role'], unique=False)

    op.execute("""
    DO $$
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'project_stage') THEN
            CREATE TYPE project_stage AS ENUM ('BUSINESS_CASE', 'DESIGN', 'CONSTRUCTION');
        END IF;
    END $$;
    """)

    op.create_table('project_stage_instances',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('stage', postgresql.ENUM('BUSINESS_CASE', 'DESIGN', 'CONSTRUCTION', name='project_stage', create_type=False), nullable=False),
    sa.Column('created_on', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_on', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.project_id'], name=op.f('fk__project_stage_instances__project_id__project')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__project_stage_instances')),
    sa.UniqueConstraint('project_id', 'stage', name='project_stage_instances_project_id_stage_key')
    )
    op.create_table('project_stage_parties',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_stage_instance_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('joint_venture_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('role_note', sa.String(), nullable=True),
    sa.Column('contract_number', sa.String(), nullable=True),
    sa.Column('created_on', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_on', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['joint_venture_id'], ['joint_ventures.id'], name=op.f('fk__project_stage_parties__joint_venture_id__joint_ventures')),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk__project_stage_parties__organization_id__organization')),
    sa.ForeignKeyConstraint(['project_stage_instance_id'], ['project_stage_instances.id'], name='fk_psp_stage_instance'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__project_stage_parties')),
    sa.UniqueConstraint('project_stage_instance_id', 'joint_venture_id', 'role', name='uq_psp_stageinst_jv_role'),
    sa.UniqueConstraint('project_stage_instance_id', 'organization_id', 'role', name='uq_psp_stageinst_org_role')
    )
    op.create_index('ix_psp_jv', 'project_stage_parties', ['joint_venture_id'], unique=False)
    op.create_index('ix_psp_org', 'project_stage_parties', ['organization_id'], unique=False)
    op.create_index('ix_psp_stageinst', 'project_stage_parties', ['project_stage_instance_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_psp_stageinst', table_name='project_stage_parties')
    op.drop_index('ix_psp_org', table_name='project_stage_parties')
    op.drop_index('ix_psp_jv', table_name='project_stage_parties')
    op.drop_table('project_stage_parties')
    op.drop_table('project_stage_instances')
    op.drop_index('project_parties_project_id_organization_id_role_idx', table_name='project_parties')
    op.drop_index('project_parties_project_id_joint_venture_id_role_idx', table_name='project_parties')
    op.drop_index('project_parties_project_id_idx', table_name='project_parties')
    op.drop_index('project_parties_organization_id_idx', table_name='project_parties')
    op.drop_index('project_parties_joint_venture_id_idx', table_name='project_parties')
    op.drop_table('project_parties')
    op.drop_table('user_roles')
    op.drop_table('role_permissions')
    op.drop_index('organization_domains_domain_idx', table_name='organization_domains')
    op.drop_table('organization_domains')
    op.drop_index('joint_venture_members_organization_id_idx', table_name='joint_venture_members')
    op.drop_index('joint_venture_members_joint_venture_id_idx', table_name='joint_venture_members')
    op.drop_table('joint_venture_members')
    op.drop_table('permissions')
    op.drop_table('joint_ventures')
    op.drop_index('audit_logs_entity_type_entity_id_performed_at_idx', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
