"""Added Code and Type to Jurisidiction table

Revision ID: 3949dec50b6b
Revises: 9a8b7c6d5e4f
Create Date: 2026-04-20 19:13:43.254776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3949dec50b6b'
down_revision: Union[str, Sequence[str], None] = '9a8b7c6d5e4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column('jurisdictions', sa.Column('code', sa.String(), nullable=True))
    op.add_column('jurisdictions', sa.Column('type', sa.String(), nullable=True))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('jurisdictions', 'type')
    op.drop_column('jurisdictions', 'code')
    
    # ### end Alembic commands ###
