"""add_bus_columns_nz_user_emissions

Revision ID: 4299170e880a
Revises: 7d0ff8b7167f
Create Date: 2026-04-28 13:41:31.106033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4299170e880a'
down_revision: Union[str, Sequence[str], None] = '7d0ff8b7167f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add bus intensity column
    op.add_column(
        "user_emissions_nz_results",
        sa.Column("bus_intensity_gco2e_km", sa.Numeric(12, 6), nullable=True),
    )
    
    # Add bus emissions column
    op.add_column(
        "user_emissions_nz_results",
        sa.Column("bus_emissions_tco2e", sa.Numeric(18, 6), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove bus emissions column
    op.drop_column("user_emissions_nz_results", "bus_emissions_tco2e")
    
    # Remove bus intensity column
    op.drop_column("user_emissions_nz_results", "bus_intensity_gco2e_km")
    # ### end Alembic commands ###
