"""Add parent_id hierarchical relationship to jurisdictions table

Revision ID: 644f003c0fa4
Revises: 3949dec50b6b
Create Date: 2026-04-20 21:25:46.933190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '644f003c0fa4'
down_revision: Union[str, Sequence[str], None] = '3949dec50b6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jurisdictions', sa.Column('parent_id', sa.UUID(), nullable=True))
    op.create_foreign_key(
        op.f('fk__jurisdictions__parent_id__jurisdictions'), 
        'jurisdictions', 
        'jurisdictions', 
        ['parent_id'], 
        ['id'],
        onupdate='CASCADE',
        ondelete='SET NULL'
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk__jurisdictions__parent_id__jurisdictions'), 'jurisdictions', type_='foreignkey')
    op.drop_column('jurisdictions', 'parent_id')
    
    # ### end Alembic commands ###
