"""aus_large_road_user_emissions

Revision ID: 7d0ff8b7167f
Revises: 0875383bb375
Create Date: 2026-04-25 13:10:47.870381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7d0ff8b7167f'
down_revision: Union[str, Sequence[str], None] = '0875383bb375'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_emissions_aus_large_road_results",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("project_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("project_stage_instance_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("project_option_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("vehicle_type", sa.String(100), nullable=False),
        sa.Column("assessment_year", sa.Integer(), nullable=False),
        # Interpolated inputs
        sa.Column("vkt_calc",           sa.Numeric(20, 6), nullable=True),
        sa.Column("speed_kph_calc",     sa.Numeric(10, 4), nullable=True),
        # Road parameters (stored for audit)
        sa.Column("gradient_m_per_km",    sa.Numeric(10, 4), nullable=True),
        sa.Column("curvature_deg_per_km", sa.Numeric(10, 4), nullable=True),
        sa.Column("iri_m_per_km",         sa.Numeric(10, 4), nullable=True),
        # Results
        sa.Column("emissions_intensity_gco2e_vkt", sa.Numeric(20, 6),  nullable=True),
        sa.Column("emissions_tco2e",               sa.Numeric(20, 10), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=False),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(
            ["project_id"], ["project.id"],
            name="fk_aus_large_road_project_id", ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_stage_instance_id"], ["project_stage_instances.id"],
            name="fk_aus_large_road_stage_instance_id", ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_option_id"], ["project_options.id"],
            name="fk_aus_large_road_option_id", ondelete="CASCADE",
        ),
        sa.UniqueConstraint(
            "project_option_id", "vehicle_type", "assessment_year",
            name="uq_aus_large_road_option_vehicle_year",
        ),
    )
    op.create_index(
        "ix_aus_large_road_option_id",
        "user_emissions_aus_large_road_results",
        ["project_option_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_aus_large_road_option_id", table_name="user_emissions_aus_large_road_results")
    op.drop_table("user_emissions_aus_large_road_results")
    # ### end Alembic commands ###
