"""Added organization_type in organizations table

Revision ID: a224bbfcb0aa
Revises: 3f7c4b74bdb4
Create Date: 2026-02-02 11:22:31.026986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'a224bbfcb0aa'
down_revision: Union[str, Sequence[str], None] = '3f7c4b74bdb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("""
    DO $$ BEGIN
      CREATE TYPE organization_type AS ENUM ('DESIGNERS', 'CONTRACTORS');
    EXCEPTION WHEN duplicate_object THEN NULL; END $$;
    """)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization', sa.Column('organization_type', postgresql.ENUM('DESIGNERS', 'CONTRACTORS', name='organization_type'), nullable=False, server_default=sa.text("'DESIGNERS'")))
    op.alter_column('project', 'proponent_org_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('project', 'created_by_user_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'created_by_user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('project', 'proponent_org_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('organization', 'organization_type')
    # ### end Alembic commands ###


    op.execute("DROP TYPE IF EXISTS organization_type CASCADE;")