"""nz_large_road_user_emissions

Revision ID: fb53ab048e95
Revises: a9b8c7d6e5f4
Create Date: 2026-05-13 13:57:39.017674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb53ab048e95'
down_revision: Union[str, Sequence[str], None] = 'a9b8c7d6e5f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_emissions_nz_large_road_results",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("project_id",                postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("project_stage_instance_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("project_option_id",         postgresql.UUID(as_uuid=True), nullable=False),
        # NZ vehicle type identifier
        sa.Column("vehicle_type", sa.String(50), nullable=False),
        sa.Column("assessment_year", sa.Integer(), nullable=False),
        # Interpolated / extrapolated inputs stored for audit
        sa.Column("vkt_calc",       sa.Numeric(20, 6), nullable=True),
        sa.Column("speed_kph_calc", sa.Numeric(10, 4), nullable=True),
        # VEPM-derived intensity (gCO2e/km)
        sa.Column("emissions_intensity_gco2e_km", sa.Numeric(12, 6), nullable=True),
        # Annual emissions = VKT × intensity / 1,000,000 (tCO2e)
        sa.Column("emissions_tco2e", sa.Numeric(18, 6), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=False),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(
            ["project_id"], ["project.id"],
            name="fk_nz_large_road_project_id", ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_stage_instance_id"], ["project_stage_instances.id"],
            name="fk_nz_large_road_stage_instance_id", ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_option_id"], ["project_options.id"],
            name="fk_nz_large_road_option_id", ondelete="CASCADE",
        ),
        sa.UniqueConstraint(
            "project_option_id", "vehicle_type", "assessment_year",
            name="uq_nz_large_road_option_vehicle_year",
        ),
    )
    op.create_index(
        "ix_nz_large_road_option_id",
        "user_emissions_nz_large_road_results",
        ["project_option_id"],
    )
    op.create_index(
        "ix_nz_large_road_stage_instance_id",
        "user_emissions_nz_large_road_results",
        ["project_stage_instance_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_nz_large_road_stage_instance_id", table_name="user_emissions_nz_large_road_results")
    op.drop_index("ix_nz_large_road_option_id",         table_name="user_emissions_nz_large_road_results")
    op.drop_table("user_emissions_nz_large_road_results")
    # ### end Alembic commands ###
